# Generated by Django 5.2.3 on 2025-06-23 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_contact', models.CharField(blank=True, max_length=15)),
                ('vehicle_type', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='other_charge',
            new_name='auto_rent',
        ),
        migrations.AlterField(
            model_name='trip',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.vehicle'),
        ),
    ]
