# Generated by Django 5.2.3 on 2025-06-24 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_trip_loading_alter_trip_loading_charge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Thalapathi Transport', max_length=100)),
                ('address', models.TextField(default='12, SNR Road, Coimbatore - 641012')),
                ('phone', models.CharField(default='+91-9876543210', max_length=15)),
                ('email', models.EmailField(default='thalapathi@example.com', max_length=254)),
                ('upi_id', models.CharField(default='thalapathi@upi', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logo/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='company/qr/')),
            ],
        ),
        migrations.AlterField(
            model_name='trip',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.vehicle'),
        ),
    ]
